version: "3.9"
services:
  fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - fpm-volume:/application

  nginx:
    image: nginx
    ports:
      - "8081:80"
    depends_on:
      - fpm
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - fpm-volume:/application

volumes:
  fpm-volume:
    driver: local
